### PR TITLE
New datasets

### PR DESCRIPTION
**Pull request by mruwnik**
For [blog.eleuther.ai](https://blog.eleuther.ai/), https://openai.com/research and [deepmind technical blog](https://www.deepmind.com/blog-categories/technical-blogs)

### CODE REVIEW

**Comment by Thomas-Lemoine** [comment]
I'm reading it rn, looks awesome!

**Comment by Thomas-Lemoine** [comment]
you can search UNINPLEMENTED_PARSERS + replace by UNIMPLEMENTED_PARSERS :p

**Review by Thomas-Lemoine — APPROVED** [review]

**Comment by mruwnik** [comment]
rebased because of conflicts.

UNINPLEMENTED_PARSERS were the ones I really didn't want to do and hoped someone else would do them...

**Review by ccstan99 — DISMISSED** [review]
I think Thomas was suggesting to fix a typo. IMPLEMENTED has an M not an N

**Comment by mruwnik** [comment]
Ah! didn't notice that. Why does N have to be right next to M?!

**Pull request merged**
