### PR TITLE
Bunch up blogs, special_docs and youtube

### PR DESCRIPTION
**Pull request by mruwnik**
https://github.com/StampyAI/alignment-research-dataset/issues/140

The special_docs, pdfs, etc. sources are all bunched together as `special_docs`. Ditto for all blogs as `blogs`, and youtube videos as `youtube`.

### CODE REVIEW

**Review by ccstan99 — COMMENTED** [review]
Can we store the original/pre-bunched dataset name in another column, i.e. source_type? Plex would like to still allow them to be tracked easily.

**Comment by mruwnik** [comment]
it's already in the meta column, but can be moved to source type. Though that will make things inconsistent, as e.g. arxviv things will have (source, source_type) = ('arxiv', 'pdf'), LW ('lesswrong', 'Greaterwrong') etc., while these would be ('blogs', 'carado.moe') etc., which is pretty much the reverse

**Comment by ccstan99** [comment]
You're right. It probably fine in metadata since we can run sql queries to generate any needed reports.

**Review by Thomas-Lemoine — APPROVED** [review]

**Review by ccstan99 — APPROVED** [review]
I updated the README file to match what I think the new list of datasets should look like. If it looks ok, I can update HF too. Closes #91

**Pull request merged**
